base_url: 'https://iss-hnm.site'
account_address: '0xD00f219132D0357Aca6B7f03FdC2F834931B30A7'
private_key: 'f3276210b2e90e8e965340104248385a33a4c1cbd0075ee370824ac70d773868'
#   "mnemonic":"cry predict flip heavy cart only smoke proof giraffe peace art skill normal obtain thunder hobby goddess right asthma hover alcohol option muscle cup"
chain_id: '54211'
user_email_def: 'haqq2022@maildrop.cc'
user_email_alt: 'haqq2023@maildrop.cc'